const TRANSACTIONS = {
  LOAD: 'TRANSACTIONS_LOAD',
  LOAD_SUCCESS: 'TRANSACTIONS_LOAD_SUCCESS',
  LOAD_FAIL: 'TRANSACTIONS_LOAD_FAIL',
};

const BASE_URL = 'http://localhost:3004';

export { TRANSACTIONS, BASE_URL };
