const TRANSACTIONS = {
  LOAD: 'TRANSACTIONS_LOAD',
  LOAD_SUCCESS: 'TRANSACTIONS_LOAD_SUCCESS',
  LOAD_FAIL: 'TRANSACTIONS_LOAD_FAIL',
  UPDATE: 'TRANSACTION_UPDATE',
  SELECT: 'TRANSACTION_SELECT',
  CLEAR: 'TRANSACTION_CLEAR',
};

const TRANSACTIONS_STATUS = {
  COMPLETED: 'COMPLETED',
  REFUNDED: 'REFUNDED',
};

const BASE_URL = 'http://localhost:3004';

export { TRANSACTIONS, TRANSACTIONS_STATUS, BASE_URL };
